### ISSUE TITLE
Bug: unable to select level occasionally

### ISSUE THREAD

**Issue by abetusk** [jbpuryear/superbubblepanic#3]
I'm having trouble reproducing but occasionally I'm unable to change click on the new level when in 'world' mode (under the campaign track).  It seems to be exacerbated when I've gone out of arcade mode and used the `X` option or when I've switched into or out of fullscreen mode, though it's not a sure thing.

The problem is intermittent.  I'm using Chromium under Linux:

```
Version 64.0.3282.167 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
```

If I'm able to reproduce the error consistently, I'll update the ticket.

**Comment by jbpuryear** [comment]
I'd be surprised if arcade mode was somehow involved. I can't think of any reason this would be the case.

Buttons work by polling the position of the reticule sprite and seeing if it's position is inside the button's bounds. When you mouseover a level select button a border should appear around it. If that isn't happening there's probably something wrong with the polling, or maybe something is weird is happening in the getBounds method. If there is a border then then probably the onDown signal isn't firing, or there's something wrong with the callback.

**Comment by abetusk** [comment]
The problem is hard to reproduce so I'm not sure what's going on.  Though I'm not sure about the arcade mode, it might be the switching of contexts, either going into and/or out of different modes or going into or out of fullscreen, maybe even taking away and giving back focus.
