### ISSUE TITLE
Glass (destroyable) platforms don't appear on metroidvania levels

### ISSUE THREAD

**Issue by abetusk** [jbpuryear/superbubblepanic#9]
On the first metroidvania (maybe the other one, I haven't looked) levels, the destroyable "glass" platforms aren't visible.  They still do collision detection and can still be destroyed by bullets (and the sound effect plays when they are destroyed) they just aren't visible.

Attached is a screenshot:

![platform](https://user-images.githubusercontent.com/1406122/37502558-b6f48ce8-28a9-11e8-84c0-630e5db6b43c.png)

**Comment by jbpuryear** [comment]
Glass platforms are drawn to the same bitmap as the splatter effect. I got rid of it on the metroid levels because it was tanking the framerate. Currently working on redesigning those levels without the glass.
